name: Build React on S3
on:
  pull_request:
    branches:
        - develop
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master  # リポジトリをチェックアウト

      - name: Install Dependencies
        run: cd app && npm install

      - name: Build
        run: npm run build  # vuejs ビルド
        working-directory: ./app

      - name: Deploy  # S3にデプロイ 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          ls
          echo $GITHUB_WORKSPACE
          aws s3 sync ./app/dist s3://website-vuejs
