name: Build React on S3
on:
  pull_request:
    branches:
        - develop
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master  # リポジトリをチェックアウト

      - name: Install Dependencies
        run: cd app && npm install

      - name: Build
        run: npm run build  # vuejs ビルド
        working-directory: ./app
        
      # S3へのデプロイ準備
      - name: Configure AWS credentials from account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          # Secretsで登録したキーを設定
          aws-access-key-id: ${{ secrets.AWS_ACCESS_TOKEN_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # S3のリージョン
          aws-region: ap-northeast-1

      - name: Deploy  # S3にデプロイ 
        run: |
          ls
          echo $GITHUB_WORKSPACE
          aws s3 sync ./app/dist s3://website-vuejs --delete
